//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Domain
{
    using System;
    
    public partial class Customer
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string StateAbbr { get; set; }
        public string ZipCode { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.DateTime UpdatedTime { get; set; }
        public int CustomerId { get; set; }
        public string LeadSource { get; set; }
        public Nullable<int> VCLRelId { get; set; }
        public Nullable<int> OfficeLocationId { get; set; }
        public string PatientCoordName { get; set; }
        public Nullable<int> DispositionId { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public Nullable<int> FireHostLeadId { get; set; }
        public Nullable<int> Five9PostQueueId { get; set; }
        public string Notes { get; set; }
        public bool Transfered { get; set; }
        public bool ViewedByClient { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public string Disposition { get; set; }
        public Nullable<bool> Opportunity { get; set; }
        public Nullable<bool> NotQualified { get; set; }
        public Nullable<int> InsuranceId { get; set; }
        public string HealthInsurance { get; set; }
        public int VerticalId { get; set; }
        public string VerticalName { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> ClientVerticalRelId { get; set; }
        public Nullable<bool> ClientByPass { get; set; }
        public string CompanyName { get; set; }
        public string Code { get; set; }
        public string ForwardPhone { get; set; }
        public string ForwardPhone2 { get; set; }
        public string Website { get; set; }
        public Nullable<bool> ClientEnabled { get; set; }
        public Nullable<bool> OfficeEnabled { get; set; }
        public string OfficeName { get; set; }
        public string OfficeAddress { get; set; }
        public string OfficeAddress2 { get; set; }
        public string OfficeCity { get; set; }
        public string OfficeState { get; set; }
        public string OfficeZipCode { get; set; }
        public Nullable<decimal> OfficeLatitude { get; set; }
        public Nullable<decimal> OfficeLongitude { get; set; }
        public string AgentNotification { get; set; }
        public string Description { get; set; }
        public Nullable<bool> StrollHealthComplete { get; set; }
    }
}
