//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceException
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> ClientVerticalRelId { get; set; }
        public Nullable<int> OfficeLocationId { get; set; }
        public int InsuranceId { get; set; }
        public bool Allow { get; set; }
        public bool Enabled { get; set; }
    }
}
