//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_CallCenterUsers
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public int UserTypeId { get; set; }
        public string UserType { get; set; }
        public int UserRoleId { get; set; }
        public string UserRole { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int AddressId { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string StateAbbr { get; set; }
        public string ZipCode { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.DateTime UpdatedTime { get; set; }
        public bool Enabled { get; set; }
        public int CallCenterUserId { get; set; }
        public Nullable<int> Five9AgentId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool ForceLogin { get; set; }
    }
}
