//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Dispositions
    {
        public int VerticalIdFlags { get; set; }
        public int DispositionId { get; set; }
        public string Disposition { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public int DispositionTypeId { get; set; }
        public string DispositionType { get; set; }
        public bool NotQualifiedDefault { get; set; }
    }
}
