//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_OfficeLocations
    {
        public int VerticalId { get; set; }
        public int ClientVerticalRelId { get; set; }
        public int BillingUserId { get; set; }
        public int OfficeLocationId { get; set; }
        public string OfficeName { get; set; }
        public int AddressId { get; set; }
        public string OfficeAddress { get; set; }
        public string OfficeAddress2 { get; set; }
        public string OfficeCity { get; set; }
        public string OfficeState { get; set; }
        public string OfficeZipCode { get; set; }
        public Nullable<decimal> OfficeLatitude { get; set; }
        public Nullable<decimal> OfficeLongitude { get; set; }
        public bool OmmitFromList { get; set; }
        public string AgentNotification { get; set; }
        public bool OfficeEnabled { get; set; }
        public int ClientId { get; set; }
        public int VCLRelId { get; set; }
        public bool ClientEnabled { get; set; }
    }
}
