//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Questions
    {
        public int VerticalId { get; set; }
        public Nullable<int> ClientVerticalRelId { get; set; }
        public Nullable<int> OfficeLocationId { get; set; }
        public int ClientRelId { get; set; }
        public int QuestionId { get; set; }
        public int SortOrder { get; set; }
        public string Question { get; set; }
        public bool Required { get; set; }
        public Nullable<int> ClientId { get; set; }
        public int VCLRelId { get; set; }
    }
}
