//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_QuesInputRuleFilters
    {
        public int InputRuleRelId { get; set; }
        public int FilterTypeId { get; set; }
        public string FilterValue { get; set; }
    }
}
