//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_QuestionInputs
    {
        public int ClientRelId { get; set; }
        public int VCLRelId { get; set; }
        public int VerticalId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> ClientVerticalRelId { get; set; }
        public Nullable<int> OfficeLocationId { get; set; }
        public int ClientInputTypeRelId { get; set; }
        public int InputTypeRelId { get; set; }
        public int InputTypeId { get; set; }
        public string InputType { get; set; }
        public Nullable<int> OptionId { get; set; }
        public string OptionValue { get; set; }
        public int OptionSortOrder { get; set; }
        public Nullable<int> ParentClientInputTypeRelId { get; set; }
    }
}
