//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_TargetTypeFilters
    {
        public int TargetTypeId { get; set; }
        public int ClientId { get; set; }
        public int ClientVerticalRelId { get; set; }
        public Nullable<int> OfficeLocationId { get; set; }
        public Nullable<int> MaxRadius { get; set; }
        public Nullable<int> SortPriority { get; set; }
        public int TargetTypeRelId { get; set; }
        public int FilterRelId { get; set; }
        public int FilterId { get; set; }
        public int FilterTypeId { get; set; }
        public string FilterValue { get; set; }
        public string FilterType { get; set; }
        public byte TargetTypeFlag { get; set; }
        public int VerticalId { get; set; }
    }
}
