//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_VerticalUsers
    {
        public int UserId { get; set; }
        public int VerticalId { get; set; }
        public string VerticalName { get; set; }
        public int VerticalTypeId { get; set; }
        public string VerticalTypeName { get; set; }
        public int UserVerticalRelId { get; set; }
        public bool UserVerticalEnabled { get; set; }
        public int SortOrder { get; set; }
    }
}
